// Shared internships mock data - used by both landing page and internships page
export const INTERNSHIPS_MOCK_DATA = [
  {
    id: "m1",
    title: "Frontend Developer Intern",
    company: "BrightApps Pvt Ltd",
    tagline: "Building the next gen SaaS",
    location: "Hyderabad",
    stipendMin: 15000,
    stipendMax: 20000,
    durationText: "3 Months",
    description: "Build responsive UI components, collaborate with designers and backend engineers to ship features. Experience with React and Tailwind CSS is mandatory.",
    skills: ["React", "Tailwind", "TypeScript", "Redux"],
    postedAgo: "3 days ago",
    feature: "Fast response",
    applicants: 120,
    category: "Engineering",
    workMode: "On-site",
    startDate: "2023-12-15",
    badge: "Hiring",
    logoColor: "bg-teal-100 text-teal-600"
  },
  {
    id: "m2",
    title: "Product Design Intern",
    company: "Creo Studio",
    tagline: "Design that speaks",
    location: "Bangalore",
    stipendMin: 10000,
    stipendMax: 15000,
    durationText: "6 Months",
    description: "Work closely with the product team to design user flows and wireframes. Proficiency in Figma and Adobe Creative Suite is required.",
    skills: ["Figma", "UI/UX", "Prototyping", "Wireframing"],
    postedAgo: "5 hours ago",
    feature: "Early Applicant",
    applicants: 45,
    category: "Design",
    workMode: "Hybrid",
    startDate: "2024-01-10",
    badge: "New",
    logoColor: "bg-purple-100 text-purple-600"
  },
  {
    id: "m3",
    title: "Backend Engineer Intern",
    company: "DataFlow Systems",
    tagline: "Scalable backend solutions",
    location: "Pune",
    stipendMin: 20000,
    stipendMax: 30000,
    durationText: "6 Months",
    description: "Assist in developing and maintaining server-side logic. You will work with Node.js and MongoDB to build scalable APIs.",
    skills: ["Node.js", "Express", "MongoDB", "AWS"],
    postedAgo: "1 week ago",
    feature: "PPO Available",
    applicants: 210,
    category: "Engineering",
    workMode: "Remote",
    startDate: "2024-01-05",
    badge: "Hot",
    logoColor: "bg-blue-100 text-blue-600"
  },
  {
    id: "m4",
    title: "Digital Marketing Intern",
    company: "Growth Hacking Co.",
    tagline: "Accelerating brand growth",
    location: "Gurgaon",
    stipendMin: 8000,
    stipendMax: 12000,
    durationText: "2 Months",
    description: "Manage social media accounts, create engaging content, and analyze marketing campaigns. Strong communication skills are a plus.",
    skills: ["SEO", "Social Media", "Google Analytics", "Canva"],
    postedAgo: "2 days ago",
    feature: "Certificate",
    applicants: 85,
    category: "Marketing",
    workMode: "Remote",
    startDate: "2023-12-20",
    badge: "Active",
    logoColor: "bg-pink-100 text-pink-600"
  },
  {
    id: "m5",
    title: "Data Science Intern",
    company: "Insight Analytics",
    tagline: "Turning data into decisions",
    location: "Mumbai",
    stipendMin: 25000,
    stipendMax: 35000,
    durationText: "6 Months",
    description: "Analyze large datasets to extract meaningful insights. Experience with Python, Pandas, and machine learning libraries is preferred.",
    skills: ["Python", "Machine Learning", "SQL", "Pandas"],
    postedAgo: "1 day ago",
    feature: "High Stipend",
    applicants: 350,
    category: "Data Science",
    workMode: "Hybrid",
    startDate: "2024-02-01",
    badge: "Popular",
    logoColor: "bg-green-100 text-green-600"
  },
  {
    id: "m6",
    title: "Content Writer Intern",
    company: "StoryTeller Media",
    tagline: "Weaving words",
    location: "Noida",
    stipendMin: 5000,
    stipendMax: 8000,
    durationText: "3 Months",
    description: "Write creative blogs and articles for our clients. Must have impeccable grammar and a flair for storytelling.",
    skills: ["Creative Writing", "Blogging", "Research", "Copywriting"],
    postedAgo: "4 hours ago",
    feature: "Flexible Hours",
    applicants: 60,
    category: "Content",
    workMode: "Remote",
    startDate: "Immediate",
    badge: "Urgent",
    logoColor: "bg-yellow-100 text-yellow-600"
  },
  {
    id: "m7",
    title: "HR Operations Intern",
    company: "People First",
    tagline: "Employees are our asset",
    location: "Chennai",
    stipendMin: 10000,
    stipendMax: 12000,
    durationText: "4 Months",
    description: "Assist the HR team in recruitment, onboarding, and employee engagement activities.",
    skills: ["Communication", "MS Office", "Recruitment", "Management"],
    postedAgo: "3 days ago",
    feature: "Letter of Rec",
    applicants: 30,
    category: "HR",
    workMode: "On-site",
    startDate: "2024-01-15",
    badge: "Hiring",
    logoColor: "bg-indigo-100 text-indigo-600"
  },
  {
    id: "m8",
    title: "Business Analyst Intern",
    company: "FinTech Corp",
    tagline: "Simplifying finance",
    location: "Bangalore",
    stipendMin: 18000,
    stipendMax: 25000,
    durationText: "6 Months",
    description: "Bridge the gap between IT and business using data analytics. Assess processes and determine requirements.",
    skills: ["Excel", "SQL", "Business Analysis", "Documentation"],
    postedAgo: "6 days ago",
    feature: "PPO Available",
    applicants: 150,
    category: "Business",
    workMode: "Hybrid",
    startDate: "2024-01-01",
    badge: "Featured",
    logoColor: "bg-orange-100 text-orange-600"
  },
  {
    id: "m9",
    title: "React Native Developer",
    company: "Appify Mobile",
    tagline: "Apps for everyone",
    location: "Remote",
    stipendMin: 15000,
    stipendMax: 22000,
    durationText: "3 Months",
    description: "Develop cross-platform mobile applications. Must be familiar with React Native and mobile UI paradigms.",
    skills: ["React Native", "JavaScript", "Mobile Dev", "API Integration"],
    postedAgo: "2 days ago",
    feature: "Remote",
    applicants: 95,
    category: "Engineering",
    workMode: "Remote",
    startDate: "2023-12-25",
    badge: "Active",
    logoColor: "bg-red-100 text-red-600"
  },
  {
    id: "m10",
    title: "Video Editor Intern",
    company: "Streamline Studios",
    tagline: "Visual storytelling",
    location: "Mumbai",
    stipendMin: 12000,
    stipendMax: 18000,
    durationText: "4 Months",
    description: "Edit high-quality video content for YouTube and social media. Proficiency in Premiere Pro or After Effects is essential.",
    skills: ["Premiere Pro", "After Effects", "Video Editing", "Color Grading"],
    postedAgo: "1 week ago",
    feature: "Creative Freedom",
    applicants: 70,
    category: "Design",
    workMode: "On-site",
    startDate: "2024-01-05",
    badge: "Hiring",
    logoColor: "bg-gray-100 text-gray-700"
  }
];

export const getTrendingInternships = () => INTERNSHIPS_MOCK_DATA.slice(0, 4);
export const getAllInternships = () => INTERNSHIPS_MOCK_DATA;
export const getInternshipById = (id) => INTERNSHIPS_MOCK_DATA.find(internship => internship.id === id);
